auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: loki
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  wal:
    enabled: true
    dir: /data/wal

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    shared_store: filesystem
    cache_location: /data/loki/cache
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem

limits_config:
  retention_period: 336h

chunk_store_config:
  max_look_back_period: 336h