version: '3.7'

services:
  service:
    build: 
      context: ./service
    networks:
      - lab3network
    depends_on:
      - rabbitmq

  api:
    build: 
      context: ./api
    ports:
      - "3000:3000"
    networks:
      - lab3network
    depends_on:
      - service

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"      # AMQP protocol port
      - "15672:15672"    # Management UI
    networks:
      - lab3network

  newman:
    image: postman/newman:alpine
    depends_on:
      - api
    volumes:
      - ./postman:/etc/newman
    entrypoint:
      - newman
    command:
      - run
      - "/etc/newman/queries.json"
      - "-r"
      - "json"
      - "--reporter-json-export"
      - "/etc/newman/output.json"
      - "--delay-request"
      - "40"  # задержка в 1000 миллисекунд, или 1 секунда, между запросами
    networks:
      - lab3network

networks:
  lab3network: